### ISSUE TITLE
Supported exe version

### ISSUE THREAD

**Issue by Keith94** [ThirteenAG/RE0.RE1.DoorSkipPlugin#1]
The plugin doesn't seem to work for my copy of RE1, I was wondering if that's because of an unsupported version or something else. I'm using this exe: [resident.evil.hd.remaster.zip](https://github.com/ThirteenAG/RE0.RE1.DoorSkipPlugin/files/1332883/codex-resident.evil.hd.remaster.zip)

**Comment by Keith94** [comment]
I did find an exe that works properly, for anyone that needs it: [REHD_SteamStubDRM_Removed.zip](https://github.com/ThirteenAG/RE0.RE1.DoorSkipPlugin/files/1339733/REHD_SteamStubDRM_Removed.zip) ([source](http://dl.atom0s.com/?dir=Game%20Specific/Resident%20Evil/Resident%20Evil%20HD%20Remaster)) That probably means v1.0 of the plugin doesn't use pattern matching.

**Comment by ThirteenAG** [comment]
It does and still works for me with steam versions. Maybe will take a look later, no promises.

**Comment by Keith94** [comment]
OK good to hear that. :) Appreciated

**Comment by Keith94** [comment]
It looks like my `rehd0.exe` [(link)](https://github.com/ThirteenAG/RE0.RE1.DoorSkipPlugin/files/1523562/resident.evil.0.hd.remaster.dlc.pack.zip) is also not compatible with the plugin, unfortunately.
