### ISSUE TITLE
Incompatible with latest patch

### ISSUE THREAD

**Issue by Keith94** [ThirteenAG/RE0.RE1.DoorSkipPlugin#2]
Can't confirm myself, but a 2018 patch may have [broke the plugin](https://pcgamingwiki.com/w/index.php?title=Resident_Evil_HD_Remaster&curid=20009&diff=685679&oldid=684763).

**Comment by ThirteenAG** [comment]
I just downloaded the game from steam, put the files and don't see anything wrong:
https://i.imgur.com/5JvzkX1.gifv

**Comment by Keith94** [comment]
Ok thanks for checking! @ThirteenAG

I'll remove the note from the wiki. :)
